"""Artifact schema package."""

from .bible import (
    BibleFileEntry,
    BibleManifest,
    CharacterBible,
    CharacterEvidence,
    CharacterRelationshipStub,
    InferredTrait,
    LocationBible,
    PropBible,
)
from .canonical_script import (
    Assumption,
    CanonicalScript,
    Invention,
    NormalizationMetadata,
)
from .continuity import (
    ContinuityEvent,
    ContinuityIndex,
    ContinuityState,
    EntityTimeline,
    StateProperty,
)
from .entity_adjudication import (
    EntityAdjudicationBatch,
    EntityAdjudicationDecision,
    EntityType,
    EntityVerdict,
)
from .graph import EntityEdge, EntityGraph
from .models import (
    Artifact,
    ArtifactHealth,
    ArtifactMetadata,
    ArtifactRef,
    CostRecord,
    DetectedValue,
    FormatClassification,
    ModelStrategy,
    ProjectConfig,
    RawInput,
    SourceFileInfo,
)
from .qa import QAIssue, QAResult
from .registry import (
    SchemaRegistry,
    ValidationErrorDetail,
    ValidationResult,
    validate_against_schema,
)
from .role import (
    PerceptionCapability,
    RoleDefinition,
    RoleResponse,
    RoleTier,
    StylePack,
    StylePackFileRef,
    StylePackSlot,
)
from .scene import (
    FieldProvenance,
    InferredField,
    NarrativeBeat,
    Scene,
    SceneIndex,
    SceneIndexEntry,
    ScriptElement,
    SourceSpan,
)
from .timeline import Timeline, TimelineEntry
from .track import TrackEntry, TrackManifest

__all__ = [
    "Artifact",
    "ArtifactHealth",
    "ArtifactMetadata",
    "ArtifactRef",
    "BibleFileEntry",
    "BibleManifest",
    "CharacterBible",
    "CharacterEvidence",
    "CharacterRelationshipStub",
    "InferredTrait",
    "LocationBible",
    "PropBible",
    "ContinuityEvent",
    "ContinuityIndex",
    "ContinuityState",
    "EntityTimeline",
    "StateProperty",
    "EntityAdjudicationBatch",
    "EntityAdjudicationDecision",
    "EntityType",
    "EntityVerdict",
    "CostRecord",
    "DetectedValue",
    "Invention",
    "Assumption",
    "NormalizationMetadata",
    "CanonicalScript",
    "EntityEdge",
    "EntityGraph",
    "SourceFileInfo",
    "FormatClassification",
    "ModelStrategy",
    "ProjectConfig",
    "RawInput",
    "QAIssue",
    "QAResult",
    "RoleDefinition",
    "RoleResponse",
    "StylePack",
    "StylePackFileRef",
    "RoleTier",
    "PerceptionCapability",
    "StylePackSlot",
    "ScriptElement",
    "SourceSpan",
    "NarrativeBeat",
    "InferredField",
    "FieldProvenance",
    "Scene",
    "SceneIndexEntry",
    "SceneIndex",
    "TimelineEntry",
    "Timeline",
    "TrackEntry",
    "TrackManifest",
    "SchemaRegistry",
    "ValidationErrorDetail",
    "ValidationResult",
    "validate_against_schema",
]
