"""Artifact schema package."""

from .bible import (
    BibleFileEntry,
    BibleManifest,
    CharacterBible,
    CharacterEvidence,
    CharacterRelationshipStub,
    InferredTrait,
    LocationBible,
    PropBible,
)
from .canonical_script import (
    Assumption,
    CanonicalScript,
    Invention,
    NormalizationMetadata,
)
from .graph import EntityEdge, EntityGraph
from .models import (
    Artifact,
    ArtifactHealth,
    ArtifactMetadata,
    ArtifactRef,
    CostRecord,
    DetectedValue,
    FormatClassification,
    ModelStrategy,
    ProjectConfig,
    RawInput,
    SourceFileInfo,
)
from .qa import QAIssue, QAResult
from .registry import (
    SchemaRegistry,
    ValidationErrorDetail,
    ValidationResult,
    validate_against_schema,
)
from .scene import (
    FieldProvenance,
    InferredField,
    NarrativeBeat,
    Scene,
    SceneIndex,
    SceneIndexEntry,
    ScriptElement,
    SourceSpan,
)

__all__ = [
    "Artifact",
    "ArtifactHealth",
    "ArtifactMetadata",
    "ArtifactRef",
    "BibleFileEntry",
    "BibleManifest",
    "CharacterBible",
    "CharacterEvidence",
    "CharacterRelationshipStub",
    "InferredTrait",
    "LocationBible",
    "PropBible",
    "CostRecord",
    "DetectedValue",
    "Invention",
    "Assumption",
    "NormalizationMetadata",
    "CanonicalScript",
    "EntityEdge",
    "EntityGraph",
    "SourceFileInfo",
    "FormatClassification",
    "ModelStrategy",
    "ProjectConfig",
    "RawInput",
    "QAIssue",
    "QAResult",
    "ScriptElement",
    "SourceSpan",
    "NarrativeBeat",
    "InferredField",
    "FieldProvenance",
    "Scene",
    "SceneIndexEntry",
    "SceneIndex",
    "SchemaRegistry",
    "ValidationErrorDetail",
    "ValidationResult",
    "validate_against_schema",
]
