"""Role-system schemas for hierarchy, runtime responses, style packs, and canon gating."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field

from .models import ArtifactRef, CostRecord


class RoleTier(StrEnum):
    """Hierarchy tier used for role authority and gating."""

    CANON_AUTHORITY = "canon_authority"
    CANON_GUARDIAN = "canon_guardian"
    STRUCTURAL_ADVISOR = "structural_advisor"
    PERFORMANCE = "performance"


class PerceptionCapability(StrEnum):
    """Media modalities a role can reason over."""

    TEXT = "text"
    IMAGE = "image"
    VIDEO = "video"
    AUDIO_VIDEO = "audio+video"


class StylePackSlot(StrEnum):
    """Whether a role accepts a style pack selection."""

    ACCEPTS = "accepts"
    FORBIDDEN = "forbidden"


class RoleDefinition(BaseModel):
    """Structured definition for an AI role persona."""

    role_id: str = Field(min_length=2)
    display_name: str = Field(min_length=2)
    tier: RoleTier
    description: str = Field(min_length=8)
    system_prompt: str = Field(min_length=20)
    capabilities: list[PerceptionCapability] = Field(min_length=1)
    style_pack_slot: StylePackSlot
    permissions: list[str] = Field(default_factory=list)


class StylePackFileRef(BaseModel):
    """Manifest entry for a style-pack file."""

    kind: Literal[
        "description",
        "reference_image",
        "frame_grab",
        "palette",
        "notes",
        "audio_reference",
    ]
    path: str = Field(min_length=1)
    caption: str | None = None


class StylePack(BaseModel):
    """Folder-based style pack manifest plus prompt material."""

    style_pack_id: str = Field(min_length=1)
    role_id: str = Field(min_length=2)
    display_name: str = Field(min_length=2)
    summary: str = Field(min_length=8)
    prompt_injection: str = Field(min_length=8)
    files: list[StylePackFileRef] = Field(default_factory=list)


class RoleResponse(BaseModel):
    """Standardized role invocation response envelope."""

    role_id: str
    content: str = Field(min_length=1)
    confidence: float = Field(ge=0.0, le=1.0)
    rationale: str = Field(min_length=1)
    decision: Literal["sign_off", "block", "override"] | None = None
    override_justification: str | None = None
    included_roles: list[str] = Field(default_factory=list)
    objections: list[str] = Field(default_factory=list)
    suggestions: list[dict[str, Any]] = Field(default_factory=list)
    suggestion_ids: list[str] = Field(default_factory=list)
    cost_data: CostRecord | None = None


class ReviewDecision(StrEnum):
    """Canon review decision for guardian and director stage reviews."""

    SIGN_OFF = "sign_off"
    BLOCK = "block"
    OVERRIDE = "override"


class ReviewReadiness(StrEnum):
    """Final stage-readiness status after guardian/director/user gating."""

    READY = "ready"
    BLOCKED = "blocked"
    AWAITING_USER = "awaiting_user"


class GuardianReview(BaseModel):
    """Canon guardian review for a scene stage."""

    role_id: Literal["script_supervisor", "continuity_supervisor"]
    decision: ReviewDecision
    summary: str = Field(min_length=1)
    rationale: str = Field(min_length=1)
    confidence: float = Field(ge=0.0, le=1.0)
    objections: list[str] = Field(default_factory=list)


class DirectorReview(BaseModel):
    """Director review and progression recommendation for a scene stage."""

    role_id: Literal["director"] = "director"
    decision: ReviewDecision
    summary: str = Field(min_length=1)
    rationale: str = Field(min_length=1)
    confidence: float = Field(ge=0.0, le=1.0)
    included_roles: list[str] = Field(default_factory=list)
    override_justification: str | None = None


class DisagreementRecord(BaseModel):
    """Preserved objection + override pair for canon-level disagreements."""

    guardian_role_id: Literal["script_supervisor", "continuity_supervisor"]
    objection_summary: str = Field(min_length=1)
    objection_rationale: str = Field(min_length=1)
    director_override_rationale: str = Field(min_length=1)
    linked_artifacts: list[ArtifactRef] = Field(default_factory=list)


class StageReviewArtifact(BaseModel):
    """Immutable stage-gating artifact generated by canon guardians + director."""

    scene_id: str = Field(min_length=1)
    stage_id: str = Field(min_length=1)
    control_mode: Literal["autonomous", "checkpoint", "advisory"]
    reviewed_artifacts: list[ArtifactRef] = Field(default_factory=list)
    guardian_reviews: list[GuardianReview] = Field(default_factory=list, min_length=2)
    director_review: DirectorReview
    disagreements: list[DisagreementRecord] = Field(default_factory=list)
    deferred_suggestions: list[ArtifactRef] = Field(default_factory=list)
    user_approved: bool | None = None
    readiness: ReviewReadiness
    reviewed_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
