"""Touched-file inventory for final-render architecture size gates."""

TOUCHED_PYTHON_FILES = (
    "benchmarks/providers/video_understanding_provider.py",
    "benchmarks/providers/video_understanding_provider_support.py",
    "benchmarks/providers/video_understanding_transport.py",
    "benchmarks/scripts/generate_final_render_provider_floor_dataset.py",
    "benchmarks/scripts/final_render_provider_floor_dataset_packets.py",
    "benchmarks/scripts/final_render_provider_floor_dataset_support.py",
    "benchmarks/scripts/final_render_provider_floor_generator_provenance.py",
    "benchmarks/scripts/final_render_provider_floor_packet_evidence.py",
    "benchmarks/scripts/final_render_provider_floor_quality_metrics.py",
    "benchmarks/scripts/final_render_provider_floor_report.py",
    "benchmarks/scripts/final_render_provider_floor_report_contract.py",
    "benchmarks/scripts/final_render_provider_floor_runtime_evidence.py",
    "benchmarks/scripts/final_render_provider_floor_retained_evidence.py",
    "benchmarks/scripts/final_render_provider_floor_runtime_snapshots.py",
    "benchmarks/scripts/final_render_provider_floor_subject_contract.py",
    "benchmarks/scripts/final_render_provider_floor_task_contract.py",
    "benchmarks/scripts/real_render_provider_floor_eval.py",
    "benchmarks/scripts/real_render_provider_floor_fixture_support.py",
    "benchmarks/scripts/real_render_provider_floor_runner_support.py",
    "benchmarks/scripts/real_render_provider_floor_support.py",
    "tests/unit/final_render_provider_floor_file_inventory.py",
    "tests/unit/final_render_provider_floor_provenance_test_support.py",
    "tests/unit/final_render_provider_floor_runtime_test_support.py",
    "tests/unit/final_render_provider_floor_snapshot_test_support.py",
    "tests/unit/final_render_provider_floor_test_support.py",
    "tests/unit/test_final_render_provider_floor_contract.py",
    "tests/unit/test_final_render_provider_floor_packet_contract.py",
    "tests/unit/test_final_render_provider_floor_runtime_snapshots.py",
    "tests/unit/test_final_render_provider_floor_subject_contract.py",
)
